#!/bin/bash

(
cd development
make clean
make
)

(
cd GuruxDLMSClientExample
mkdir obj
mkdir bin
make clean
make
)

if [ "$1" != "armhf" -a "$1" != "i386" -a "$1" != "amd64" ]; then
    echo nutno zadat architekturu armhf nebo i386 nebo amd64
    exit
    fi

ARCH=$1
VERZE=1.0.0
APPNAME=dlms-client

mkdir -p debian/usr/bin


DIR=/tmp/dlms-client.$$
(
rm -fr $DIR
find debian -print | cpio -pudm $DIR
sed "s/XXXX/$VERZE/; s/AAAA/$ARCH/;" < debian-control > $DIR/debian/DEBIAN/control 
cp GuruxDLMSClientExample/bin/gurux.dlms.client.bin $DIR/debian/usr/bin/dlms-client
cd $DIR
fakeroot dpkg-deb --build debian
)

mv $DIR/debian.deb $APPNAME-$VERZE-$ARCH.deb
rm -fr $DIR

